<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DKH\eBaySDK\Test\Order\Types;

use DKH\eBaySDK\Order\Types\InitiateCheckoutSessionRestRequest;

class InitiateCheckoutSessionRestRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new InitiateCheckoutSessionRestRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\DKH\eBaySDK\Order\Types\InitiateCheckoutSessionRestRequest', $this->obj);
    }

    public function testExtendsCreateSignInCheckoutSessionRequest()
    {
        $this->assertInstanceOf('\DKH\eBaySDK\Order\Types\CreateSignInCheckoutSessionRequest', $this->obj);
    }
}
