<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DKH\eBaySDK\Trading\Types;

/**
 *
 * @property \DKH\eBaySDK\Trading\Types\CountryDetailsType[] $CountryDetails
 * @property \DKH\eBaySDK\Trading\Types\CurrencyDetailsType[] $CurrencyDetails
 * @property \DKH\eBaySDK\Trading\Types\DispatchTimeMaxDetailsType[] $DispatchTimeMaxDetails
 * @property \DKH\eBaySDK\Trading\Types\PaymentOptionDetailsType[] $PaymentOptionDetails
 * @property \DKH\eBaySDK\Trading\Types\RegionDetailsType[] $RegionDetails
 * @property \DKH\eBaySDK\Trading\Types\ShippingLocationDetailsType[] $ShippingLocationDetails
 * @property \DKH\eBaySDK\Trading\Types\ShippingServiceDetailsType[] $ShippingServiceDetails
 * @property \DKH\eBaySDK\Trading\Types\SiteDetailsType[] $SiteDetails
 * @property \DKH\eBaySDK\Trading\Types\TaxJurisdictionType[] $TaxJurisdiction
 * @property \DKH\eBaySDK\Trading\Types\URLDetailsType[] $URLDetails
 * @property \DKH\eBaySDK\Trading\Types\TimeZoneDetailsType[] $TimeZoneDetails
 * @property \DKH\eBaySDK\Trading\Types\ItemSpecificDetailsType[] $ItemSpecificDetails
 * @property \DKH\eBaySDK\Trading\Types\RegionOfOriginDetailsType[] $RegionOfOriginDetails
 * @property \DKH\eBaySDK\Trading\Types\ShippingPackageDetailsType[] $ShippingPackageDetails
 * @property \DKH\eBaySDK\Trading\Types\ShippingCarrierDetailsType[] $ShippingCarrierDetails
 * @property \DKH\eBaySDK\Trading\Types\ReturnPolicyDetailsType $ReturnPolicyDetails
 * @property \DKH\eBaySDK\Trading\Types\ListingStartPriceDetailsType[] $ListingStartPriceDetails
 * @property \DKH\eBaySDK\Trading\Types\SiteBuyerRequirementDetailsType[] $BuyerRequirementDetails
 * @property \DKH\eBaySDK\Trading\Types\ListingFeatureDetailsType[] $ListingFeatureDetails
 * @property \DKH\eBaySDK\Trading\Types\VariationDetailsType $VariationDetails
 * @property \DKH\eBaySDK\Trading\Types\ExcludeShippingLocationDetailsType[] $ExcludeShippingLocationDetails
 * @property \DateTime $UpdateTime
 * @property \DKH\eBaySDK\Trading\Types\RecoupmentPolicyDetailsType[] $RecoupmentPolicyDetails
 * @property \DKH\eBaySDK\Trading\Types\ShippingCategoryDetailsType[] $ShippingCategoryDetails
 * @property \DKH\eBaySDK\Trading\Types\ProductDetailsType $ProductDetails
 */
class GeteBayDetailsResponseType extends \DKH\eBaySDK\Trading\Types\AbstractResponseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'CountryDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\CountryDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'CountryDetails'
        ],
        'CurrencyDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\CurrencyDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'CurrencyDetails'
        ],
        'DispatchTimeMaxDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\DispatchTimeMaxDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'DispatchTimeMaxDetails'
        ],
        'PaymentOptionDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\PaymentOptionDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'PaymentOptionDetails'
        ],
        'RegionDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\RegionDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'RegionDetails'
        ],
        'ShippingLocationDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ShippingLocationDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ShippingLocationDetails'
        ],
        'ShippingServiceDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ShippingServiceDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ShippingServiceDetails'
        ],
        'SiteDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\SiteDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'SiteDetails'
        ],
        'TaxJurisdiction' => [
            'type' => 'DKH\eBaySDK\Trading\Types\TaxJurisdictionType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'TaxJurisdiction'
        ],
        'URLDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\URLDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'URLDetails'
        ],
        'TimeZoneDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\TimeZoneDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'TimeZoneDetails'
        ],
        'ItemSpecificDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ItemSpecificDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ItemSpecificDetails'
        ],
        'RegionOfOriginDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\RegionOfOriginDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'RegionOfOriginDetails'
        ],
        'ShippingPackageDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ShippingPackageDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ShippingPackageDetails'
        ],
        'ShippingCarrierDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ShippingCarrierDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ShippingCarrierDetails'
        ],
        'ReturnPolicyDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ReturnPolicyDetailsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ReturnPolicyDetails'
        ],
        'ListingStartPriceDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ListingStartPriceDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ListingStartPriceDetails'
        ],
        'BuyerRequirementDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\SiteBuyerRequirementDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'BuyerRequirementDetails'
        ],
        'ListingFeatureDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ListingFeatureDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ListingFeatureDetails'
        ],
        'VariationDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\VariationDetailsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VariationDetails'
        ],
        'ExcludeShippingLocationDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ExcludeShippingLocationDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ExcludeShippingLocationDetails'
        ],
        'UpdateTime' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UpdateTime'
        ],
        'RecoupmentPolicyDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\RecoupmentPolicyDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'RecoupmentPolicyDetails'
        ],
        'ShippingCategoryDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ShippingCategoryDetailsType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ShippingCategoryDetails'
        ],
        'ProductDetails' => [
            'type' => 'DKH\eBaySDK\Trading\Types\ProductDetailsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ProductDetails'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
