<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DKH\eBaySDK\Order\Types;

/**
 *
 * @property \DKH\eBaySDK\Order\Types\CreditCard $creditCard
 * @property \DKH\eBaySDK\Order\Types\LineItemInput[] $lineItemInputs
 * @property \DKH\eBaySDK\Order\Types\ShippingAddress $shippingAddress
 */
class CreateSignInCheckoutSessionRequest extends \DKH\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'creditCard' => [
            'type' => 'DKH\eBaySDK\Order\Types\CreditCard',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'creditCard'
        ],
        'lineItemInputs' => [
            'type' => 'DKH\eBaySDK\Order\Types\LineItemInput',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'lineItemInputs'
        ],
        'shippingAddress' => [
            'type' => 'DKH\eBaySDK\Order\Types\ShippingAddress',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingAddress'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
