<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DKH\eBaySDK\Test\BulkDataExchange\Types;

use DKH\eBaySDK\BulkDataExchange\Types\AbortRecurringJobExecutionRequest;

class AbortRecurringJobExecutionRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new AbortRecurringJobExecutionRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\DKH\eBaySDK\BulkDataExchange\Types\AbortRecurringJobExecutionRequest', $this->obj);
    }

    public function testExtendsBaseServiceRequest()
    {
        $this->assertInstanceOf('\DKH\eBaySDK\BulkDataExchange\Types\BaseServiceRequest', $this->obj);
    }
}
